## DESARROLLO
spring.datasource.url=jdbc:oracle:thin:@192.168.10.21:1521:movildev
spring.datasource.username=pasajes
spring.datasource.password=PsjMB$252

## PRODUCTIVO
#spring.datasource.url=jdbc:oracle:thin:@192.168.10.224:1521:MOVIL
#spring.datasource.username=pasajes
#spring.datasource.password=movil16
#spring.datasource.hikari.connectionTimeout=60000