
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MEFEService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.10.24:8086/MEFEService.svc?wsdl")
//@WebServiceClient(name = "MEFEService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.10.25:8085/MEFEService.svc?wsdl")
public class MEFEService
    extends Service
{

    private final static URL MEFESERVICE_WSDL_LOCATION;
    private final static WebServiceException MEFESERVICE_EXCEPTION;
    private final static QName MEFESERVICE_QNAME = new QName("http://tempuri.org/", "MEFEService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.10.24:8086/MEFEService.svc?wsdl");
            //url = new URL("http://192.168.10.25:8085/MEFEService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEFESERVICE_WSDL_LOCATION = url;
        MEFESERVICE_EXCEPTION = e;
    }

    public MEFEService() {
        super(__getWsdlLocation(), MEFESERVICE_QNAME);
    }

    public MEFEService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEFESERVICE_QNAME, features);
    }

    public MEFEService(URL wsdlLocation) {
        super(wsdlLocation, MEFESERVICE_QNAME);
    }

    public MEFEService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEFESERVICE_QNAME, features);
    }

    public MEFEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MEFEService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMEFEService
     */
    @WebEndpoint(name = "BasicHttpBinding_IMEFEService")
    public IMEFEService getBasicHttpBindingIMEFEService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IMEFEService"), IMEFEService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMEFEService
     */
    @WebEndpoint(name = "BasicHttpBinding_IMEFEService")
    public IMEFEService getBasicHttpBindingIMEFEService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IMEFEService"), IMEFEService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEFESERVICE_EXCEPTION!= null) {
            throw MEFESERVICE_EXCEPTION;
        }
        return MEFESERVICE_WSDL_LOCATION;
    }

}
